routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');

Route::get('/Autism-Centre', 'CentreController@autism')->name('Autism.centre');
Route::get('/Special-Education-Centre', 'CentreController@specialeducation')->name('SpecialEducation.centre');


Route::get('/Skill-Development-Centre', 'CentreController@skilldevelopment')->name('SkillDevelopment.centre');
Route::get('/Kindergarten', 'CentreController@Kindergarten')->name("Kindergarten.centre");
Route::get('/training','TrainingController@index')->name('training.index');
Route::get('/services/apna-fun-club','ServicesController@ApnaFunClub')->name('services.apna-fun-club');
Route::get('/research','ResearchController@index')->name('research.index');
Route::get('/about-us/board-members', 'AboutController@page_board_members')->name('About.Board_Members');
Route::get('/volunteer','PagesController@volunteer')->name('pages.volunteer');
Route::get('/vacancy','PagesController@vacancy')->name('pages.vacancy');
Route::get('/contact','PagesController@contact')->name('pages.contact');

// Shop
// Cart Routes

Route::group(['prefix' => 'shop'], function()
{
  Route::get('/', 'ShopController@index')->name('shop.index');
  Route::get('filter/{id}','ShopController@filter')->name('shop.filter');
  Route::post('checkout','CartController@checkout')->name('shop.checkout');
  Route::post('checkout/confirm','CartController@confirm')->name('shop.confirm');

  Route::get('details/{id}', 'ShopController@show')->name('shop.details');

  Route::get('cart', 'CartController@index')->name('Shop.cart');
  Route::post('cart', 'CartController@store')->name('cart.store');
  Route::delete('cart/{id}', 'CartController@destroy')->name('cart.destroy');
});



//Route::get('/admin', 'Admin\AdminController@index')->name('admin.index');

//Achievements
Route::get('/achievements/organization', 'AchievementController@organization')->name('Organization.achievements');
Route::get('/achievements/students-alumni', 'AchievementController@students_alumni')->name('students-alumni.achievements');
Route::get('/achievements/media-coverage', 'AchievementController@media_coverage')->name('media_coverage.achievements');
Route::get('/achievements/recognition', 'AchievementController@recognition')->name('recognition.achievements');

//Services
Route::get('/services/nios', 'ServicesController@nios')->name('Services.nios');
Route::get('/services/boys-hostel', 'ServicesController@boys_hostel')->name('Services.boys-hostel');

Route::get('/donation', 'DonateController@page_donate')->name('donate.page');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/events', 'EventsController@index')->name('events');



// Panels
Route::group(['prefix' => 'webpanel',  'middleware' => 'auth'], function()
{
    Route::get('/','Panel\PanelController@index')->name('panel.index');
    Route::get('categories','Panel\CategoryController@index')->name('panel.category.index');
    Route::get('categories/create','Panel\CategoryController@create')->name('panel.category.create');
    Route::post('categories/create','Panel\CategoryController@store')->name('panel.category.store');
    Route::post('categories/delete','Panel\CategoryController@delete')->name('panel.category.delete');
    Route::resource('products', 'Panel\ProductController');
    Route::resource('orders','Panel\OrderController');
    Route::get('catagories/edit/{id}', 'Panel\CategoryController@edit')->name('panel.catagory.edit');
    Route::post('categories/edit/{id}', 'Panel\CategoryController@update')->name('panel.category.update');
    Route::post('order/delivery','Panel\OrderController@delivery')->name('order.delivery');
    Route::post('order/cancel','Panel\OrderController@cancel')->name('order.cancel');

});

app/Http/Controllers/Panel/CategoryController.php
<?php

namespace App\Http\Controllers\Panel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Session;
use App\Category;

class CategoryController extends Controller
{
    //
    public function index(){
      $category=DB::table('categories')->get();
      return view ('panel.categories.index')->withCategories($category);
    }
    public function create(){
      return view ('panel.categories.create');
    }
    public function edit($id){
      $category=Category::find($id);
      return view ('panel.categories.edit')->withCategory($category);
    }
    public function store(Request $request){
      $this->validate($request,[
        'name' => 'required',
        ]);
        $flag = DB::table('categories')->insert(['name'=>$request->input('name')]);
        if($flag){
          $request->session()->flash('success', 'Category Create Successful');
        }
        else{
            $request->session()->flash('fail', 'Failed to Store');
        }
        return redirect()->route('panel.category.index');
    }
    public function delete(Request $request){
      $flag =DB::table('categories')->where('id',$request->input('id'))->delete();
      if($flag){
        $request->session()->flash('success', 'Successfully Deleted');
      }
      else{
          $request->session()->flash('fail', 'Failed to Delete');
      }
      return redirect()->route('panel.category.index');

    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
          'name' => 'required',
        ]);

        // Product Table Filling Up
        $category = Category::find($id);

        $category->name = $request->name;


        $category->save();

        Session::flash('success', 'Product has been edited successfully !');
        return redirect()->route('panel.category.index');
    }
}

app/Http/Controllers/Panel/OrderController.php
<?php

namespace App\Http\Controllers\Panel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Session;

class OrderController extends Controller
{
    //
    public function index(){
      $orders=DB::table('orders')
                  ->join('buyers','orders.buyer_id','=','buyers.id')
                  ->select('orders.*','buyers.*','orders.id as order_id')
                  ->orderBy('orders.id','DESC')
                  ->get();
      return view('panel.orders.index')->withOrders($orders);
    }
    public function show($id){
      $details=DB::table('order_details')
                  ->join('products','order_details.product_id','=','products.id')
                  ->select('products.*','order_details.*','order_details.quantity as order_quantity')
                  ->where('order_details.order_id',$id)
                  ->get();
      $status=DB::table('orders')
                  ->select('status','id')
                  ->where('id',$id)
                  ->first();
                  //dd($status);
      return view('panel.orders.details')->withDetails($details)
                                         ->withStatus($status);
    }
    public function delivery(Request $request){
      DB::table('orders')->where('id',$request->order_id)->update(['status'=>1]);
      $details=DB::table('order_details')
                  ->join('products','order_details.product_id','=','products.id')
                  ->select('products.*','order_details.*','order_details.quantity as order_quantity')
                  ->where('order_details.order_id',$request->order_id)
                  ->get();
      foreach($details as $detail){
        DB::table('products')->where('id',$detail->product_id)->decrement('quantity',$detail->order_quantity);
      }
      Session::flash('success', 'Delivery successfully made');
      return redirect()->route('orders.index');
    }
    public function cancel(Request $request){
      DB::table('orders')->where('id',$request->order_id)->update(['status'=>3]);
      $details=DB::table('order_details')
                  ->join('products','order_details.product_id','=','products.id')
                  ->select('products.*','order_details.*','order_details.quantity as order_quantity')
                  ->where('order_details.order_id',$request->order_id)
                  ->get();
      foreach($details as $detail){
        DB::table('products')->where('id',$detail->product_id)->increment('quantity',$detail->order_quantity);
      }
      Session::flash('success', 'Delivery successfully canceled');
      return redirect()->route('orders.index');
    }
}

app/Http/Controllers/Panel/PanelController.php
<?php

namespace App\Http\Controllers\Panel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Session;

class PanelController extends Controller
{
    //
    public function index(){
      $categories=DB::table('categories')->get();
      return view('panel.index')->withCategories($categories);
    }
}

app/Http/Controllers/Panel/ProductController.php
<?php

namespace App\Http\Controllers\Panel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;
use App\Product;
use App\Category;
use App\RelCatProd;

use Session;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all(['id', 'name', 'quantity', 'price', 'status']);
        return view('panel.products.index')->with('products', $products);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all(['id', 'name']);
        return view('panel.products.create')->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
          'name' => 'required',
          'category_id' => 'required',
          'quantity' => 'required',
          'price' => 'required',
        ]);

        // Product Table Filling Up
        $product = new Product;

        $product->category_id = $request->category_id;
        $product->name = $request->name;
        $product->description = $request->description;
        $product->quantity = $request->quantity;
        $product->price = $request->price;
        $product->tags = $request->tags;
        $product->options = $request->options;

        $product->save();
        $id=Product::orderBy('id','desc')->first();
        Session::flash('success', 'Product has been added successfully !');

        $input=$request->all();
        $images=array();
    if($files=$request->file('images')){
        for($k=0;$k<count($files);$k++){
            $name=$id->id.'_'.$k.'.'.$files[$k]->getClientOriginalExtension();
            $files[$k]->move(public_path('images\products'),$name);
            $images[]=$name;
            DB::table('images')->insert(['product_id'=>$id->id,'image'=>$name]);
        }
    }

        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::with('category')->find($id);
        $categories = Category::all(['id', 'name']);
        return view('panel.products.edit')->with('categories', $categories)->with('product', $product);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
          'name' => 'required',
          'category_id' => 'required',
          'quantity' => 'required',
          'price' => 'required'
        ]);

        // Product Table Filling Up
        $product = Product::find($id);

        $product->category_id = $request->category_id;
        $product->name = $request->name;
        $product->description = $request->description;
        $product->quantity = $request->quantity;
        $product->price = $request->price;
        $product->tags = $request->tags;
        $product->options = $request->options;

        $product->save();

        Session::flash('success', 'Product has been edited successfully !');
        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
      $product = Product::find($request->id);

      $product->delete();

      Session::flash('success', 'Product has been deleted successfully !');
      return redirect()->route('products.index');
    }
}

resources/views/panel/orders/details.blade.php
@extends('panel.layouts.main')
@section('content')
<div class="content-wrapper">
  <div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{{ route('panel.index') }}">Dashboard</a>
      </li>
      <li class="breadcrumb-item">
        <a href="{{ route('orders.index') }}">Order List</a>
      </li>
      <li class="breadcrumb-item active">Order Details</li>
    </ol>
    <!-- Icon Cards-->
    <div>
      @if($status->status === 0)
        <form method="POST" action="{{route('order.delivery')}}">
          {{ csrf_field() }}
          <input type="hidden" name="order_id" value="{{ $status->id }}" />
          <button type="submit" class="btn btn-sm btn-success">Make Delivery
        </form>
      @elseif($status->status === 1)
      <form method="POST" action="{{route('order.cancel')}}">
        {{ csrf_field() }}
        <input type="hidden" name="order_id" value="{{ $status->id }}" />
        <button type="submit" class="btn btn-sm btn-danger">Cancel
      </form>
      @endif
    </div>

    <br>


    <!-- Example DataTables Card-->
    <div class="card mb-3">
      <div class="card-header">
        <i class="fa fa-table"></i> Product List</div>
      <div class="card-body">
        @if($details)
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>Name</th>
                <th>Image</th>
                <th>Quantity</th>
                <th>Total</th>
                <th>Option</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>Name</th>
                <th>Image</th>
                <th>Quantity</th>
                <th>Total</th>
                <th>Option</th>
              </tr>
            </tfoot>
            <tbody>
              @foreach($details as $detail)
                <tr>
                  <td>{{ $detail->name }}</td>
                  <td>  <center><img src="{{asset('images/products/'.$detail->product_id.'_0.jpg')}}" alt="Flowers" height="50px"></center></td>
                  <td>{{ $detail->order_quantity }}</td>
                  <td>{{ $detail->total }}</td>
                  <td>
                    @if($status->status === 0)
                      <span class="text-warning">Pending</span>
                    @elseif($status->status === 1)
                      <span class="text-success">Delivered</span>
                    @else
                      <span class="text-danger">Canceled</span>
                    @endif
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
        @else
          <center>No orders Yet !</center>
        @endif

      </div>
      <div class="card-footer small text-muted">Updated from Database</div>
    </div>
  </div>
  <!-- /.container-fluid-->
  <!-- /.content-wrapper-->
  @endsection

resources/views/panel/orders/index.blade.php
@extends('panel.layouts.main')
@section('content')
<div class="content-wrapper">
  <div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{{ route('panel.index') }}">Dashboard</a>
      </li>
      <li class="breadcrumb-item active">Order List</li>
    </ol>
    <!-- Icon Cards-->

    <br>

    <!-- Example DataTables Card-->
    <div class="card mb-3">
      <div class="card-header">
        <i class="fa fa-table"></i> Order List</div>
      <div class="card-body">
        @if($orders)
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Amount</th>
                <th>Option</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Amount</th>
                <th>Option</th>
              </tr>
            </tfoot>
            <tbody>
              @foreach($orders as $order)
                <tr>
                  <td>{{ $order->code }}</td>
                  <td>{{ $order->fullname }}</td>
                  <td>{{ $order->email }}</td>
                  <td>{{ $order->phone }}</td>
                  <td>{{ $order->address }}</td>
                  <td>{{ $order->total }}</td>
                  <td>
                    @if($order->status === 0)
                      <span class="text-warning">Pending</span>
                    @elseif($order->status === 1)
                      <span class="text-success">Completed</span>
                    @else
                      <span class="text-danger">Canceled</span>

                    @endif
                    <a href="{{route('orders.show',[$order->order_id])}}" class="btn btn-sm btn-primary">Details</a>
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
        @else
          <center>No orders Yet !</center>
        @endif

      </div>
      <div class="card-footer small text-muted">Updated from Database</div>
    </div>
  </div>
  <!-- /.container-fluid-->
  <!-- /.content-wrapper-->
@endsection